spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/batuyirtici/Config-Server
server:
  port: 8888