spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/batuyirtici/Rent-a-Car-Microservice/tree/master/config-server-dev-and-prod
server:
  port: 8888